name: TerraControl
version: 0.0.1
description: Advanced custom world generator. Based on Khorn's TerrainControl, which is based on R-T-B's PhoenixTerrainMod, which itself is based on Bucyruss' BiomeTerrainMod.
authors: ['Timethor']
main: com.timethor.terracontrol.bukkit.TerraPlugin
load: startup
commands:
    terra:
        description: TerraControl commands
        usage: |
              /<command> <check> [world] - Checks TC is enable for this world.
              /<command> <reload> [world] - Reload config
              /<command> <biome> [-f] - Show current chunk biome and block stats
              /<command> <list> - Show list of loaded BOB's 
              /<command> <map> - Generate a biome map image
              /<command> <spawn> [BobName] - Spawn a BOB with BobName at your cursor
        aliases: [terracontrol]
permissions:
    terra.*:
        default: false
        children:
            tc.cmd.*: true
    terra.cmd.*:
        default: false
        children:
            terra.cmd.biome: true
            terra.cmd.check: true
            terra.cmd.help: true
            terra.cmd.list: true
            terra.cmd.map: true
            terra.cmd.reload: true
            terra.cmd.spawn: true
    terra.cmd.biome:
        default: op
        description: show chunk biome and block stats
    terra.cmd.check:
        default: op
        description: check/create TC settings for world
    terra.cmd.help:
        default: op
        description: show help
    terra.cmd.list:
        default: op
        description: list bo2 objects
    terra.cmd.map:
        default: op
        description: generate biome map image
    terra.cmd.reload:
        default: op
        description: reload world settings
    terra.cmd.spawn:
        default: op
        description: spawn bo2 where you look